[JENKINS-63584] Add an option to use Jenkins proxy to access Kubernetes
jenkinsci/kubernetes-plugin pull request #836
Opened 2020-09-03 14:11 UTC by inidona

2020-09-03 14:15 UTC, Vlatombe requested changes
This should be an option at the Kubernetes Cloud level. If the master is deployed in the same Kubernetes cluster as the agents it will provision, this would cause it to use the configured proxy instead of targetting directly the Kubernetes API.

2020-09-03 14:20 UTC, inidona commented
> This should be an option at the Kubernetes Cloud level. If the master is deployed in the same Kubernetes cluster as the agents it will provision, this would cause it to use the configured proxy instead of targetting directly the Kubernetes API.

Do you mean a checkbox at cloudconfig that jenkins proxy should be used ?

2020-09-03 14:29 UTC, Vlatombe commented
Yes.

2020-09-09 07:59 UTC, Vlatombe reviewed
Some minor reviews and a question. Otherwise, this lgtm.

2020-09-09 07:59 UTC, Vlatombe commented on src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
> +import jenkins.model.Jenkins;
Remove unused imports

2020-09-09 07:59 UTC, Vlatombe commented on src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
> +import org.junit.runner.RunWith;
Ditto

2020-09-09 07:59 UTC, Vlatombe commented on src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
> +
Revert

2020-09-09 07:59 UTC, Vlatombe commented on src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
> +            Jenkins jenkins = Jenkins.getInstanceOrNull(); // this code might run on slaves
Not really.

2020-09-09 07:59 UTC, Vlatombe commented on src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
> +                    builder.withWebsocketTimeout(10000);
Why this?

2020-09-10 15:49 UTC, inidona commented on src/test/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapterTest.java
> +
class reverted

2020-09-10 15:50 UTC, inidona commented on src/main/java/org/csanchez/jenkins/plugins/kubernetes/KubernetesFactoryAdapter.java
> +            Jenkins jenkins = Jenkins.getInstanceOrNull(); // this code might run on slaves
comment removed

2020-09-11 08:06 UTC, Vlatombe approved these changes

2020-09-11 08:06 UTC, merged

2021-06-11 15:46 UTC, pashcan commented
Greetings,
Why does [JENKINS-63584](https://issues.jenkins.io/browse/JENKINS-63584) show **Fixed but Unreleased** if this was merged many moons ago?
I am actually seeing configured proxy being ignored when trying to reach remote cluster, so I'm wondering if this in fact made it into plugin. Despite having toggled Use Jenkins Proxy checkbox, I am seeing in the logs ```org.csanchez.jenkins.plugins.kubernetes.KubernetesFactoryAdapter
Proxy Settings for Cloud: false```

2021-06-11 18:05 UTC, inidona commented
@pashcan i don´t know why the issue is not resolved, but the release works for me as expected. 
I found out for  communication we had to use websockets and the proxy and maybe the reverse proxy before your k8s cluster must support websockets too.

2021-11-02 05:56 UTC, duemir commented
@pashcan it looks like "Test Connection" was not updated so it doesn't take into account the "Jenkins Proxy" flag defaulting to `false`, i.e. don't use.

2021-11-09 04:25 UTC, duemir commented
I tried to fix "Test Connection" in #1064